name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Publie sur PyPI quand un tag commençant par 'v' est poussé

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build the package
      run: python setup.py sdist bdist_wheel

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__  # Utilisez __token__ pour l'authentification
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}  # Le token PyPI que vous devez ajouter en tant que secret
      run: twine upload dist/*
